imports:
  - { resource: ./../repositories.yml }
  - { resource: ./../common.yml }

services:
  _defaults:
    public: true

  psgdpr.service.export:
    class: PrestaShop\Module\Psgdpr\Service\ExportService
    arguments:
      - "@psgdpr.service.logger"
      - '@=service("prestashop.adapter.legacy.context").getContext()'
      - '@=service("prestashop.adapter.legacy.context").getContext().getTranslator()'
