imports:
  - { resource: repositories.yml }

services:
  _defaults:
    public: true

  psgdpr.service.export:
    class: PrestaShop\Module\Psgdpr\Service\ExportService

  psgdpr.service.customer:
    class: PrestaShop\Module\Psgdpr\Service\CustomerService
    arguments:
      - '@=service("prestashop.adapter.legacy.context").getContext()'
      - '@=service("prestashop.adapter.legacy.context").getContext().currentLocale'
      - '@=service("prestashop.adapter.legacy.context").getContext().getTranslator()'
      - "@psgdpr.repository.cart"
      - "@psgdpr.repository.order"
      - '@=service("prestashop.adapter.legacy.context").getContext().link'

  psgdpr.service.logger:
    class: PrestaShop\Module\Psgdpr\Service\LoggerService
    arguments:
      - "@psgdpr.repository.logger"
