services:
  _defaults:
    public: true

  Psgdpr:
    class: "Psgdpr"
    factory: ["Module", "getInstanceByName"]
    arguments:
      - "psgdpr"

  PrestaShop\Module\Psgdpr\Repository\LoggerRepository:
    class: 'PrestaShop\Module\Psgdpr\Repository\LoggerRepository'
    arguments:
      - "@Doctrine\\Persistence\\ManagerRegistry"

  PrestaShop\Module\Psgdpr\Repository\CustomerRepository:
    class: 'PrestaShop\Module\Psgdpr\Repository\CustomerRepository'
    arguments:
      - "@doctrine.dbal.default_connection"

  PrestaShop\Module\Psgdpr\Service\LoggerService:
    class: 'PrestaShop\Module\Psgdpr\Service\LoggerService'
    arguments:
      - "@PrestaShop\\Module\\Psgdpr\\Repository\\LoggerRepository"
      - "@PrestaShop\\Module\\Psgdpr\\Repository\\CustomerRepository"

  PrestaShop\Module\Psgdpr\Service\ExportCustomerData\ExportCustomerDataService:
    class: 'PrestaShop\Module\Psgdpr\Service\ExportCustomerData\ExportCustomerDataService'
    arguments:
      - '@=service("prestashop.adapter.legacy.context").getContext()'
      - '@=service("Psgdpr").getTranslator()'

  PrestaShop\Module\Psgdpr\Service\ExportCustomerData\ExportCustomerDataFactory:
    class: 'PrestaShop\Module\Psgdpr\Service\ExportCustomerData\ExportCustomerDataFactory'
    arguments:
      - !tagged_iterator psgdpr.export.customerData

  PrestaShop\Module\Psgdpr\Service\ExportCustomerData\ExportCustomerDataToCsv:
    class: 'PrestaShop\Module\Psgdpr\Service\ExportCustomerData\ExportCustomerDataToCsv'
    tags: ["psgdpr.export.customerData"]
    arguments:
      - '@=service("prestashop.adapter.legacy.context").getContext()'
      - '@PrestaShop\Module\Psgdpr\Service\LoggerService'

  PrestaShop\Module\Psgdpr\Service\ExportCustomerData\ExportCustomerDataToPdf:
    class: 'PrestaShop\Module\Psgdpr\Service\ExportCustomerData\ExportCustomerDataToPdf'
    tags: ["psgdpr.export.customerData"]
    arguments:
      - '@=service("prestashop.adapter.legacy.context").getContext()'
      - '@PrestaShop\Module\Psgdpr\Service\LoggerService'

  PrestaShop\Module\Psgdpr\Service\ExportCustomerData\ExportCustomerDataToJson:
    class: 'PrestaShop\Module\Psgdpr\Service\ExportCustomerData\ExportCustomerDataToJson'
    tags: ["psgdpr.export.customerData"]
    arguments:
      - '@=service("prestashop.adapter.legacy.context").getContext()'
      - '@PrestaShop\Module\Psgdpr\Service\LoggerService'
