services:
  _defaults:
    public: true

  psgdpr.module:
    class: "Psgdpr"
    factory: ["Module", "getInstanceByName"]
    arguments:
      - "psgdpr"

  psgdpr.service.logger:
    class: PrestaShop\Module\Psgdpr\Service\LoggerService
    arguments:
      - "@psgdpr.repository.logger"
      - "@psgdpr.repository.customer"
