services:
  _defaults:
    public: true

  psgdpr.repository.logger:
    class: 'PrestaShop\Module\Psgdpr\Repository\LoggerRepository'
    arguments:
      - "@doctrine.orm.entity_manager"

  psgdpr.repository.cart:
    class: 'PrestaShop\Module\Psgdpr\Repository\CartRepository'
    arguments:
      - "@doctrine.dbal.default_connection"

  psgdpr.repository.cartrule:
    class: 'PrestaShop\Module\Psgdpr\Repository\CartRuleRepository'
    arguments:
      - "@doctrine.dbal.default_connection"

  psgdpr.repository.customer:
    class: 'PrestaShop\Module\Psgdpr\Repository\CustomerRepository'
    arguments:
      - "@doctrine.dbal.default_connection"

  psgdpr.repository.order:
    class: 'PrestaShop\Module\Psgdpr\Repository\OrderRepository'
    arguments:
      - "@doctrine.dbal.default_connection"

  psgdpr.repository.consent:
    class: 'PrestaShop\Module\Psgdpr\Repository\ConsentRepository'
    arguments:
      - "@doctrine.dbal.default_connection"
      - "@doctrine.orm.entity_manager"
