## Issue with autowiring of services ##
# Automatic service resolution via "resource" parameter currently does not work, so we have to use intermediate way.
# it will work when we PrestaShop 8.1 will be released
# more informations here: https://symfony.com/doc/current/service_container/import.html

services:
  _defaults:
    public: false
    autowire: true
    autoconfigure: true
    bind:
      $context: '@=service("prestashop.adapter.legacy.context").getContext()'
      $commandBus: "@prestashop.core.command_bus"
      $queryBus: "@prestashop.core.query_bus"
      $translator: '@=service("Psgdpr").getTranslator()'
      $defaultGroupProvider: "@prestashop.adapter.group.provider.default_groups_provider"
      $hashing: "@hashing"

  ## SERVICES ##
  Psgdpr:
    class: "Psgdpr"

  PrestaShop\Module\Psgdpr\Service\LoggerService:
    class: 'PrestaShop\Module\Psgdpr\Service\LoggerService'

  PrestaShop\Module\Psgdpr\Service\ExportCustomerData\ExportCustomerDataService:
    class: 'PrestaShop\Module\Psgdpr\Service\ExportCustomerData\ExportCustomerDataService'

  PrestaShop\Module\Psgdpr\Service\CustomerService:
    class: 'PrestaShop\Module\Psgdpr\Service\CustomerService'

  ## REPOSITORIES ##
  PrestaShop\Module\Psgdpr\Repository\LoggerRepository:
    class: 'PrestaShop\Module\Psgdpr\Repository\LoggerRepository'

  PrestaShop\Module\Psgdpr\Repository\CartRepository:
    class: 'PrestaShop\Module\Psgdpr\Repository\CartRepository'

  PrestaShop\Module\Psgdpr\Repository\CartRuleRepository:
    class: 'PrestaShop\Module\Psgdpr\Repository\CartRuleRepository'

  PrestaShop\Module\Psgdpr\Repository\CustomerRepository:
    class: 'PrestaShop\Module\Psgdpr\Repository\CustomerRepository'

  PrestaShop\Module\Psgdpr\Repository\OrderRepository:
    class: 'PrestaShop\Module\Psgdpr\Repository\OrderRepository'

  PrestaShop\Module\Psgdpr\Repository\OrderInvoiceRepository:
    class: 'PrestaShop\Module\Psgdpr\Repository\OrderInvoiceRepository'

  PrestaShop\Module\Psgdpr\Repository\ConsentRepository:
    class: 'PrestaShop\Module\Psgdpr\Repository\ConsentRepository'

  ## CONTROLLERS ##
  PrestaShop\Module\Psgdpr\Controller\Admin\CustomerController:
    class: 'PrestaShop\Module\Psgdpr\Controller\Admin\CustomerController'
    public: true

  PrestaShop\Module\Psgdpr\Controller\Admin\DownloadCustomerInvoicesController:
    class: 'PrestaShop\Module\Psgdpr\Controller\Admin\DownloadCustomerInvoicesController'
    public: true

  PrestaShop\Module\Psgdpr\Service\ExportCustomerData\ExportCustomerDataToCsv:
    class: 'PrestaShop\Module\Psgdpr\Service\ExportCustomerData\ExportCustomerDataToCsv'
    tags: ["psgdpr.export.customerData"]

  PrestaShop\Module\Psgdpr\Service\ExportCustomerData\ExportCustomerDataToPdf:
    class: 'PrestaShop\Module\Psgdpr\Service\ExportCustomerData\ExportCustomerDataToPdf'
    tags: ["psgdpr.export.customerData"]

  PrestaShop\Module\Psgdpr\Service\ExportCustomerData\ExportCustomerDataToJson:
    class: 'PrestaShop\Module\Psgdpr\Service\ExportCustomerData\ExportCustomerDataToJson'
    tags: ["psgdpr.export.customerData"]

  PrestaShop\Module\Psgdpr\Service\ExportCustomerData\ExportCustomerDataFactory:
    class: 'PrestaShop\Module\Psgdpr\Service\ExportCustomerData\ExportCustomerDataFactory'
    arguments:
      - !tagged_iterator psgdpr.export.customerData

  PrestaShop\Module\Psgdpr\Service\CustomerDataResponder\CustomerDataResponderByCustomerId:
    class: 'PrestaShop\Module\Psgdpr\Service\CustomerDataResponder\CustomerDataResponderByCustomerId'
    tags: ["psgdpr.export.responder"]

  PrestaShop\Module\Psgdpr\Service\CustomerDataResponder\CustomerDataResponderByEmail:
    class: 'PrestaShop\Module\Psgdpr\Service\CustomerDataResponder\CustomerDataResponderByEmail'
    tags: ["psgdpr.export.responder"]

  PrestaShop\Module\Psgdpr\Service\CustomerDataResponder\CustomerDataResponderByPhone:
    class: 'PrestaShop\Module\Psgdpr\Service\CustomerDataResponder\CustomerDataResponderByPhone'
    tags: ["psgdpr.export.responder"]

  PrestaShop\Module\Psgdpr\Service\CustomerDataResponder\CustomerDataResponderFactory:
    class: 'PrestaShop\Module\Psgdpr\Service\CustomerDataResponder\CustomerDataResponderFactory'
    arguments:
      - !tagged_iterator psgdpr.export.responder

  ## old binding with this->get() ##
  psgdpr.repository.consent:
    alias: 'PrestaShop\Module\Psgdpr\Repository\ConsentRepository'
    public: true
    deprecated: ~

  psgdpr.repository.logger:
    alias: 'PrestaShop\Module\Psgdpr\Repository\LoggerRepository'
    public: true
    deprecated: ~
